### ISSUE TITLE
Soul Brazier crashing server

### ISSUE THREAD

**Issue by Woif1990** [nekosune/Thaumic_Exploration#14]
Server was crashed when a player placed the Soul Brazier, I don't have access to the crash log but I assume it's similar to: https://github.com/Flaxbeard/Thaumic_Exploration/issues/28
(Mostly putting this issue here since I'm not sure if you check the old flaxbeard github for it.)

Edit: have a crashlog now: http://pastebin.com/gc43ut6t

**Comment by jmazouri** [comment]
Also having this issue, for some reason it's trying to open a UI on the server. I don't know forge APIs so I can't help much more, unfortunately, but here's a crash log:

http://pastebin.com/NhjMEKmA

**Comment by blockbreaker1361** [comment]
Try using the latest versions of Thaumcraft and Thaumic Exploration. I believe these problems have been fixed in them.

**Comment by Creysys** [comment]
It is not im using the latest Thaumcraft with ThaumicTinkerer-2.5-1.7.10-439

im getting the same crash.

**Comment by nekosune** [comment]
It needs the latest Thaumic Exploration Not Thaumic Tinkerer

**Comment by Keridos** [comment]
happens with latest version of both mods for me as well.
