### ISSUE TITLE
Game crashes on load java.lang.NoClassDefFoundError: thaumcraft/common/blocks/JarStepSound

### ISSUE THREAD

**Issue by nolimet** [nekosune/Thaumic_Exploration#18]
http://pastebin.com/7fKC0cwL

It seems the mod makes a null reference to a asset in thaumcraft that does not exists. I traced it back to thaumic exploration on line 16.

Could you please look into it?

**Comment by nekosune** [comment]
It's already fixed please update before reporting issues
