### ISSUE TITLE
1.7.2 - Messed Up Thaumonomicon

### ISSUE THREAD

**Issue by Peach774** [nekosune/Thaumic_Exploration#2]
In the new version (1.0.2) that fixed compatibility with the updated Thaumic tinkerer, all icons that are not the squares that you have to do the research minigame for are missing.

**Comment by tkdberger** [comment]
Are you using a resource pack?

**Comment by Peach774** [comment]
Probably a grpahics card issue but no one is developing for 1.7.2 anymore. Please don't necro tkdberger
