### ISSUE TITLE
Replicator and Seals not working?

### ISSUE THREAD

**Issue by ryukra** [nekosune/Thaumic_Exploration#22]
I noticed that the seals and the replicator are not working. 
Using the latest build ThaumicExploration-1.7.10-1.1-37.jar

**Comment by reiniken** [comment]
Same boat

**Comment by renadi** [comment]
Seals don't work, specifically in MP at least

**Comment by Qohelethh** [comment]
Seals don't work in SMP. Any chance this will get fixed?

**Comment by smbarbour** [comment]
Duplicate of #11

**Comment by Unrepentant-Atheist** [comment]
Where can I download the furthest fork compiled for 1.7.10?
