### ISSUE TITLE
taintberry right click crashes the game null pointer exception

### ISSUE THREAD

**Issue by ghost** [nekosune/Thaumic_Exploration#30]
do you need crash?

ThaumicExploration-1.7.10-1.1-47 (the only one that works for me)

**Comment by GaeaKat** [comment]
yes, I would need crash but from an up to date version  for all I know the error is fixed already

**Comment by ghost** [comment]
i cant run .53 version game doesnt start

**Comment by GaeaKat** [comment]
That is the more important error, bear in mind if later versions do not run for you, how would you run a version with this fixed?

**Comment by ghost** [comment]
@nekosune  see my other report made a new 1 for it. when is fixed or if i can run a newer build i will try this again and confirm this bug (taintberry) is fixed.

**Comment by ghost** [comment]
@nekosune  indeed has been fixed sorry 4 the trouble

**Comment by GaeaKat** [comment]
@trollworkout sorry for my bluntness, just found out today my laptop repair is too expensive, so kind of grumpy :)

**Comment by ghost** [comment]
@nekosune  is alright . sorry about that. i been using a broken laptop for over a year now. i have to use exernal keyboard on it as my laptop's keyboard is busted. yea. so i know how that feels. no $$$ to fix it :/
