### ISSUE TITLE
everfull urn extra blocks support in config + ability to hydrate tilled soil

### ISSUE THREAD

**Issue by ghost** [nekosune/Thaumic_Exploration#31]
that would be great 

// every  3 sec it creates a fake right click water bucket event on the added blocks
"additional everfull urn blocks"=witchery:cauldron, minecraft:cauldron

**Comment by GaeaKat** [comment]
Too laggy, the tilled soil however may be a good idea

**Comment by Shahelion** [comment]
Is there another way to add support for those blocks? They work similar to the Crucible in terms of filling, except the Witchery Cauldron requires three buckets.
