### ISSUE TITLE
can't seem to be able to run any build past .47 

### ISSUE THREAD

**Issue by ghost** [nekosune/Thaumic_Exploration#32]
the game loads then exists nothing happens no crash log no error

**Comment by GaeaKat** [comment]
Still need the log it will be in the minecraft directory

**Comment by ghost** [comment]
@nekosune  i will try .53 see if i can get a log 4 u

**Comment by ghost** [comment]
@nekosune i got something in the logs looks like this:
logs/

fml-client-latest.log 
http://pastebin.com/XrUVnVv2

fml-junk-earlystartup.log:
[07:32:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07:32:00] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07:32:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker

latest.log: 

that's it. nothing in crash.
forge 1448 recommended 1.7.10
about 48 mods well really 30 but  2 of them have child mods

**Comment by ghost** [comment]
seems to want codechicken.core.launch.DepLoader but i dont have or use nei. is nei required to run this mod. seems to work fine without it and codechicken core build .47 and previous

**Comment by GaeaKat** [comment]
in .48 I needed to use Code chicken lib , if you download Code chicken lib http://files.minecraftforge.net/maven/codechicken/CodeChickenLib/1.7.10-1.1.3.140/CodeChickenLib-1.7.10-1.1.3.140-universal.jar
and add it should work

**Comment by ghost** [comment]
@nekosune  running now. i didnt know codechicken is required.

**Comment by ghost** [comment]
@nekosune .53 works

**Comment by GaeaKat** [comment]
@trollworkout it was supposed to use thaumcraft's copy of the DepLoader to download Code Chicken lib for you, seems that is not working correctly, the only reason this hasnt come up before is seems no one plays without NEI anymore

**Comment by ghost** [comment]
@nekosune  interesting  i use crafguide and never had to use nei. thanks.
